name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check out code
        uses: actions/checkout@v2
      - name: caching deps
        run: deno cache --lock=deps-lock.json deps.ts
      - name: compiling executable
        run: deno compile --allow-read --allow-run --target=${{ matrix.deno-target }} --output=tmuxed ./entry-point.ts
      - name: uploading artifact
        uses: actions/upload-artifact@v2
        with:
          name: tmuxed-${{ matrix.deno-target }}
          path: tmuxed

